theme: jekyll-theme-cayman
title: [EMG - Based Virtual Input via Machine Learning]
description: [implementing real-time hand gesture recognition to control miscellaneous devices]
defaults:
  # _docs
  - scope:
      path: ""
      type: docs
    values:
      sidebar:
        nav: "docs"
