theme: jekyll-theme-cayman
values:
  topnav: navigation
title: [EMG - Based Virtual Input via Machine Learning]
description: [implementing real-time hand gesture recognition to control miscellaneous devices]
