title: Real-Time sEMG Gesture Recognition of Natural Movement for Expression in Personal Devices and IoT
author: Michael Kim
email: mhk150230@g.ucla.edu
author2: Viacheslav Inderiakin
email2: v.inderiakin.uk@gmail.com
    
    
description: A New Form of Mobile and Robust Human-Computer Interaction
show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to https://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

  # generate social links in footer
  social_links:
    twitter: ucla
    github:  M202A
    rss: ucla

header_pages:
 - index.md
 - about.md
 - previousworks.md
 - methods.md
 - workbreakdown.md 
 - implementation.md
 - futuredirection.md
 - references.md

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
